### PR TITLE
Not everyone have `authbind` utility in a Linux distribution

### PR DESCRIPTION
**Pull request by BoQsc**
It's true.

### CODE REVIEW

**Comment by DannyArends** [comment]
Would this work ? 
e.g. does Debian 10 allow you to bind ports 80/443 as a user (not sudo/root) ?

**Comment by BoQsc** [comment]
> e.g. does Debian 10 allow you to bind ports 80/443 as a user (not sudo/root) ?

Thanks for pointing that. 
I'll test it out tomorrow. 
(For the most part I'm just a regular root user.)

**Comment by DannyArends** [comment]
Yeah please check, I was under the impression you either need root/sudo or authbind. 

Let me know if it works, the bash scripts in the sh/ folder are just there so I can quickly shutdown and reboot the server when updating the let's encrypt certificates without having to look up the exact commands in the readme file 😆

**Comment by BoQsc** [comment]
I'm kind of late this time, the draft got corrupted next day and only now I had time to rewrite it.
The minimal changes I've pushed: do work well on Debian 10.  

What the ./sh/run does now:
Launches the DaNode web server on :8080 port if the user is not with root privilegies.
(Also, informs about the ways to launch the DaNode web server as Root user to allow binding to :80 port)
```
Starting DaNode Web Server with port :8080 as a Regular Linux User
Please switch to root user to bind to port :80
(Use 'sudo' if your Linux Distribution supports it)
(Otherwise: use 'su root' to switch to the root user)
```


I can try to automate it: to detect if distribution has `sudo` on their distribution and prompt for it.  
But I think the script is already getting hard to read.

BTW: You can close this Pull Request if you think all this is just unnecessary.

**Pull request closed without merging**
